chore: environment configuration
SoftDevSix/Argos pull request #2
Opened 2024-10-15 12:06 UTC by teran-joseluis

#### Resolved task/US: ([item title]())
* * * *

## What's in this pull request?

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2024-10-15 12:37 UTC, zrock-dev commented
Dear @teran-joseluis @gabygabylagaby @ronaldo-mendoza-jalafund 

Please fill the PR description in order to understand what changes you are requesting to merge.

2024-10-15 13:01 UTC, zrock-dev commented
I'm guessing this PR is related with the ticket [CS-17 [SP-0] : Continuous integration](https://app.clickup.com/t/868a6f4cf) But the proposed change set is a configuration of spring boot environments.

2024-10-15 20:26 UTC, teran-joseluis commented
> Dear @teran-joseluis @gabygabylagaby @ronaldo-mendoza-jalafund
> 
> Please fill the PR description in order to understand what changes you are requesting to merge.

Just updated it. Would you mind to review it now please?

2024-10-15 20:30 UTC, teran-joseluis commented
> I'm guessing this PR is related with the ticket [CS-17 [SP-0] : Continuous integration](https://app.clickup.com/t/868a6f4cf) But the proposed change set is a configuration of spring boot environments.

Yeah, @zamoranoalicia requested the configuration of these different environments in the daily syncs. I don't know if you remember about it.

2024-10-15 20:33 UTC, teran-joseluis commented
> Dear @teran-joseluis @gabygabylagaby @ronaldo-mendoza-jalafund
> 
> Please fill the PR description in order to understand what changes you are requesting to merge.

I almost forgot... I worked on this, could you remove my other teammates please?

2024-10-15 20:47 UTC, zrock-dev requested changes
Could it be possible to also update the docker-compose files with the postgreSQL instances?

2024-10-15 20:47 UTC, zrock-dev commented on src/main/resources/application-stage.properties
I believe that this environment is used by QA for a release candidate branch, but we do not have QA

2024-10-16 03:56 UTC, salet-gutierrez-jalafund requested changes

2024-10-16 03:56 UTC, salet-gutierrez-jalafund commented on src/main/resources/application.properties
> +spring.profiles.active=dev
You mention this in your description:

```
3 different environments were created where each one has its database (not set it yet due to the project doesn't contain the required dependencies) and its port set it.

To view the different environment, just run the application class and it will start on the default one, which is dev environment according the properties file set it for now.

To change between the environments, in the main properties file change the content after the equal, like below:
Running on port 8080:

spring.profiles.active=dev
Running on port 8081:

spring.profiles.active=stage
Running on port 8082:

spring.profiles.active=prod
```
It would be good if in this part of the code you make an include like the following example:

```
spring.profiles.active=dev
spring.profiles.include=prod,stage
```

In this case, the dev profile will be the main profile, but the prod and stage profiles configurations will also be included.

However, it would be good if you ask your group about it.

If you want to read more, you can go to these two links: [https://docs.spring.io/spring-boot/reference/features/profiles.html#features.profiles.adding-active-profiles](https://docs.spring.io/spring-boot/reference/features/profiles.html#features.profiles.adding-active-profiles)

[https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/boot-features-profiles.html](https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/boot-features-profiles.html)

2024-10-30 22:13 UTC, teran-joseluis commented on src/main/resources/application-stage.properties
It won't be used for QA, it will be used to ensure that all new changes deployed from previous environments are working as intended.

2024-10-30 22:14 UTC, teran-joseluis commented on src/main/resources/application.properties
> +spring.profiles.active=dev
I don't think it's a good idea to include the configurations from other environments since each one will be managed separately.

2024-10-30 22:31 UTC, closed without merging