Feature/cs 018 2/detect harcoded values
SoftDevSix/Argos pull request #45
Opened 2024-11-26 10:46 UTC by fabian-romero-jalafund

#### Resolved task/US: ([CS-018-02 [SP-3]: Detect hardcoded values with line number](https://app.clickup.com/t/868awhe80))
* * * *

## What's in this pull request?
Implementation to detect the hardcoded values in a java code with also the line number

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Unit tests were added to the implemented classes

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/SoftDevSix/Argos/45)

2024-11-26 13:49 UTC, leonardo-herrera-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/HardcodedValueMatcher.java
> +    private Pattern pattern;
Pattern should be final.

2024-11-26 13:49 UTC, leonardo-herrera-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/analyzer/BlockAnalyzer.java
> +    public static synchronized BlockAnalyzer getInstance() {
What is the need to use Singleton pattern? It can cause bottlenecks with many analysis at the same time.

2024-11-27 11:43 UTC, leonardo-herrera-jalafund requested changes
The `final` values should not considered hard coded.

2024-11-28 00:17 UTC, axel-ayala-jalafund requested changes

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/HardcodedDetection.java
> +@Getter
Use `@Value` notation instead of `@Getter` and `@ToString`

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/MethodDetectionStrategy.java
> +    public MethodDetectionStrategy(){
Delete constructor and use `@Value`

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/ConstructorDetectionStrategy.java
> +    public ConstructorDetectionStrategy(){
Delete this constructor and use `@Value`

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/ConstructorDetectionStrategy.java
> +public class ConstructorDetectionStrategy implements IDetectionStrategy {
Use `@Value` notation

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/MethodDetectionStrategy.java
> +public class MethodDetectionStrategy implements IDetectionStrategy {
Use `@Value` notation

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/AttributeDetectionStrategy.java
> +                    if (modifiers.noneMatch(mod -> mod.equals("final")) && matcher.isHardcoded(attributeValue)) {
Avoid magic values `"final"`, put into a `private static final`

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/AttributeDetectionStrategy.java
> +    public void detectHardcodedValues(JavaParser.ClassBodyDeclarationContext member,
This method is too long, split it.

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/DetectorStrategyContext.java
> +@AllArgsConstructor
Replace with `@Value`

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/DetectorStrategyContext.java
> +public class DetectorStrategyContext {
Class name could be more clear like `HardcodedDetector`

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/IDetectionStrategy.java
> +public interface IDetectionStrategy {
Maybe it could be generic <N> instead of `JavaParser.ClassBodyDeclarationContext`, but if you don't use it for different nodes, we can maintain it like this following the YAGNI principle.

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/analyzer/BlockAnalyzer.java
> +    private static BlockAnalyzer instance;
The `instance` variable is never used, should be removed

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/analyzer/BlockAnalyzer.java
> +                String[] arguments = methodArgumentValue.split("\\s*,\\s*");
Regex extract it to a constant

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/analyzer/BlockAnalyzer.java
> +                    HardcodedDetection detection = HardcodedDetection.builder().hardcodedValue(assignmentValue)
This builder is repeated in 3 methods, extract it into helper method

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/analyzer/BlockAnalyzer.java
> +                if(matcher.isHardcoded(assignmentValue)){
This if is repeated in 3 methods, extract it

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/HardcodedValueMatcher.java
> +    public static synchronized HardcodedValueMatcher getInstance() {
Is necessary `synchronized`, if you will use concurrency in the future it's OK

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/HardcodedValueMatcher.java
> +    private static HardcodedValueMatcher instance;
Is necessary singleton? Maybe use Dependency Injection instead

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/test/java/edu/usb/argos/ASTProcessor/bestpractices/HardcodedValueDetectorTest.java
> +//        assertEquals(4, detector.getHardcodedValues().size());
Deleted this lines codes, or uncomment lines

2024-11-28 00:17 UTC, axel-ayala-jalafund commented on ASTProcessor/src/test/java/edu/usb/argos/ASTProcessor/bestpractices/HardcodedValueDetectorTest.java
> +//        assertTrue(detector.getHardcodedValues().contains("100"));
Deleted this lines codes, or uncomment lines

2024-12-03 04:12 UTC, fabian-romero-jalafund commented on ASTProcessor/src/main/java/edu/usb/argos/ASTProcessor/bestpractices/hardcodeddetection/IDetectionStrategy.java
> +public interface IDetectionStrategy {
No more nodes will be analyzed.

2024-12-03 11:43 UTC, zamoranoalicia approved these changes
LGTM

2024-12-03 12:59 UTC, axel-ayala-jalafund approved these changes

2024-12-03 22:59 UTC, leonardo-herrera-jalafund approved these changes

2024-12-03 22:59 UTC, merged